// Tests de journald — parser de logs binarios de systemd-journald (.journal).
//
// Verificación con ORÁCULO horneada: el fixture es un .journal **COMPACT** fabricado
// spec-exacto y LEÍDO con **journalctl** (systemd, implementación independiente) durante
// el desarrollo — `journalctl --file ... -o export` emite las 3 entradas con TODOS sus
// campos (hash jenkins lookup3 válido), y mi parser coincide byte-a-byte (3/3). Embebido
// en base64 → npm test offline. El núcleo se cruzó además vs journalctl sobre journals
// REALES de este WSL: user-1000.journal (76 entradas) y system.journal (2234 entradas),
// MESSAGE/_PID/_COMM/_SYSTEMD_UNIT/PRIORITY/realtime IDÉNTICOS, 0 errores de parseo.
//
// El fixture tiene 3 entradas con contenido forense: systemd (sesión), sudo (comando con
// privilegios) y sshd (login fallido desde IP externa).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { journald as J } from '../src/tools/journald.js';

const B64 = 'TFBLU0hIUkgAAAAAEAAAAAAAAAAAAAAAKB9qTUDcTv2vfVWvxBqjzPEiFIqv8kYOkpjsd9gBaOBWpJjwTXFBopqv4YmsV8U57h/nZvm+QmGpYYL4AcHozhABAAAAAAAAbAsAAAAAAAAgAQAAAAAAAEAAAAAAAAAAcAEAAAAAAABAAAAAAAAAAFgMAAAAAAAAHwAAAAAAAAADAAAAAAAAAAMAAAAAAAAAAQAAAAAAAABYDAAAAAAAAABAHhgkCgYAgNa2GCQKBgCA1rYYJAoGABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgMAAADAAAA+AsAAAAAAAAEAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABZAAAAAAAAAP+dSGylXCizAAAAAAAAAAAAAAAAAAAAAPgEAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAX1RSQU5TUE9SVD1zeXNsb2cAAAAAAAAAAQAAAAAAAABSAAAAAAAAAKMmjYAZn/CAAAAAAAAAAAAAAAAAAAAAAPgEAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAUFJJT1JJVFk9NgAAAAAAAAEAAAAAAAAAYQAAAAAAAABgASlOsvHvawAAAAAAAAAAAAAAAAAAAAD4BAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAFNZU0xPR19JREVOVElGSUVSPXN5c3RlbWQAAAAAAAAAAQAAAAAAAABOAAAAAAAAAMTY4oM+hxQZAAAAAAAAAAAAAAAAAAAAAPgEAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAX1BJRD0xAAABAAAAAAAAAE4AAAAAAAAACkyvOE3D3owAAAAAAAAAAAAAAAAAAAAA+AQAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABfVUlEPTAAAAEAAAAAAAAAVQAAAAAAAADC4ghFF0sMTQAAAAAAAAAAAAAAAAAAAAD4BAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAF9DT01NPXN5c3RlbWQAAAABAAAAAAAAAGAAAAAAAAAAwtmgNAFSH/YAAAAAAAAAAAAAAAAAAAAA+AQAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABfU1lTVEVNRF9VTklUPWluaXQuc2NvcGUBAAAAAAAAAG8AAAAAAAAAgzcakcPG7OIAAAAAAAAAAAAAAAAAAAAA+AQAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABNRVNTQUdFPVN0YXJ0ZWQgU2Vzc2lvbiAxIG9mIHVzZXIgcm9vdC4AAQAAAAAAAABZAAAAAAAAAL0buZ6pnm9YAAAAAAAAAAAAAAAAAAAAAPgEAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAX0hPU1ROQU1FPWZveC1sYWIAAAAAAAAAAwAAAAAAAABkAAAAAAAAAAEAAAAAAAAAAEAeGCQKBgAAQB4YJAoGAFakmPBNcUGimq/hiaxXxTnMOapnATdtzLABAAAQAgAAaAIAANACAAAgAwAAcAMAAMgDAAAoBAAAmAQAAAAAAAABAAAAAAAAAFkAAAAAAAAA/51IbKVcKLMAAAAAAAAAAAAAAAAAAAAAiAgAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABfVFJBTlNQT1JUPXN5c2xvZwAAAAAAAAABAAAAAAAAAFIAAAAAAAAAQ4BY6lkiwxUAAAAAAAAAAAAAAAAAAAAAiAgAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABQUklPUklUWT01AAAAAAAAAQAAAAAAAABeAAAAAAAAAEvGGpcdwliHAAAAAAAAAAAAAAAAAAAAAIgIAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAU1lTTE9HX0lERU5USUZJRVI9c3VkbwAAAQAAAAAAAABRAAAAAAAAAL39PtaXkzJwAAAAAAAAAAAAAAAAAAAAAIgIAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAX1BJRD0yMDQ4AAAAAAAAAAEAAAAAAAAAUQAAAAAAAAC3IZD1yrwDiQAAAAAAAAAAAAAAAAAAAACICAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAF9VSUQ9MTAwMAAAAAAAAAABAAAAAAAAAFIAAAAAAAAAy8LNb71CFMMAAAAAAAAAAAAAAAAAAAAAiAgAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABfQ09NTT1zdWRvAAAAAAAAAQAAAAAAAACiAAAAAAAAAGSgbrywu3vTAAAAAAAAAAAAAAAAAAAAAIgIAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAATUVTU0FHRT0gIGR1c3QgOiBUVFk9cHRzLzAgOyBQV0Q9L2hvbWUvZHVzdCA7IFVTRVI9cm9vdCA7IENPTU1BTkQ9L3Vzci9iaW4vY2F0IC9ldGMvc2hhZG93AAAAAAAAAQAAAAAAAABZAAAAAAAAAL0buZ6pnm9YAAAAAAAAAAAAAAAAAAAAAIgIAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAX0hPU1ROQU1FPWZveC1sYWIAAAAAAAAAAwAAAAAAAABgAAAAAAAAAAIAAAAAAAAAQItqGCQKBgBAi2oYJAoGAFakmPBNcUGimq/hiaxXxTnvfr5/GPSCkGAFAADABQAAGAYAAHgGAADQBgAAKAcAAIAHAAAoCAAAAQAAAAAAAABZAAAAAAAAAP+dSGylXCizAAAAAAAAAAAAAAAAAAAAAPgLAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAX1RSQU5TUE9SVD1zeXNsb2cAAAAAAAAAAQAAAAAAAABSAAAAAAAAAEOAWOpZIsMVAAAAAAAAAAAAAAAAAAAAAPgLAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAUFJJT1JJVFk9NQAAAAAAAAEAAAAAAAAAXgAAAAAAAAC3xJOTeEKKfgAAAAAAAAAAAAAAAAAAAAD4CwAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAFNZU0xPR19JREVOVElGSUVSPXNzaGQAAAEAAAAAAAAAUQAAAAAAAAA43FjUar4AYgAAAAAAAAAAAAAAAAAAAAD4CwAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAF9QSUQ9MzEyMAAAAAAAAAABAAAAAAAAAE4AAAAAAAAACkyvOE3D3owAAAAAAAAAAAAAAAAAAAAA+AsAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABfVUlEPTAAAAEAAAAAAAAAUgAAAAAAAABp6m7jvQee1QAAAAAAAAAAAAAAAAAAAAD4CwAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAF9DT01NPXNzaGQAAAAAAAABAAAAAAAAAJcAAAAAAAAAMsSFyZCHvUkAAAAAAAAAAAAAAAAAAAAA+AsAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABNRVNTQUdFPUZhaWxlZCBwYXNzd29yZCBmb3IgaW52YWxpZCB1c2VyIGFkbWluIGZyb20gMjAzLjAuMTEzLjcgcG9ydCA1MTU0MiBzc2gyAAEAAAAAAAAAWQAAAAAAAAC9G7meqZ5vWAAAAAAAAAAAAAAAAAAAAAD4CwAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAF9IT1NUTkFNRT1mb3gtbGFiAAAAAAAAAAMAAAAAAAAAYAAAAAAAAAADAAAAAAAAAIDWthgkCgYAgNa2GCQKBgBWpJjwTXFBopqv4YmsV8U533wmTSdf8/LoCAAASAkAAKAJAAAACgAAWAoAAKgKAAAACwAAmAsAAAYAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAPgEAACICAAA+AsAAA==';
const bytes = () => new Uint8Array(Buffer.from(B64, 'base64'));

test('header: journal válido, COMPACT, 3 entradas', () => {
  const r = J.parse(bytes());
  assert.equal(r.ok, true);
  assert.equal(r.header.compact, true);
  assert.equal(r.count, 3);
  assert.equal(r.parseErrors, 0);
  assert.equal(r.header.machineId, 'f122148aaff2460e9298ec77d80168e0');
});

test('entrada 1: campos vs journalctl', () => {
  const e = J.parse(bytes()).entries[0];
  assert.equal(e.seqnum, 1);
  assert.equal(J.realtimeIso(e.realtime), '2023-11-14T22:13:20.000Z');
  assert.equal(e.fields._COMM, 'systemd');
  assert.equal(e.fields.PRIORITY, '6');
  assert.equal(e.fields.MESSAGE, 'Started Session 1 of user root.');
  assert.equal(e.fields._SYSTEMD_UNIT, 'init.scope');
});

test('entrada 2: sudo con UID/PID', () => {
  const e = J.parse(bytes()).entries[1];
  assert.equal(e.fields._COMM, 'sudo');
  assert.equal(e.fields._PID, '2048');
  assert.equal(e.fields._UID, '1000');
  assert.match(e.fields.MESSAGE, /COMMAND=\/usr\/bin\/cat \/etc\/shadow/);
});

test('entrada 3: sshd login fallido', () => {
  const e = J.parse(bytes()).entries[2];
  assert.equal(e.fields._COMM, 'sshd');
  assert.match(e.fields.MESSAGE, /Failed password for invalid user admin from 203\.0\.113\.7/);
});

test('hallazgos forenses: sudo + SSH fallido detectados', () => {
  const r = J.parse(bytes());
  const sudo = r.forensic.find(f => /sudo/.test(f.tag));
  const ssh = r.forensic.find(f => /SSH login fallido/.test(f.tag));
  assert.ok(sudo, 'detecta el uso de sudo');
  assert.ok(ssh, 'detecta el login SSH fallido');
});

test('seqnums en orden 1..3', () => {
  const r = J.parse(bytes());
  assert.deepEqual(r.entries.map(e => e.seqnum), [1, 2, 3]);
});

test('no-journal: error limpio', () => {
  const r = J.parse(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]));
  assert.equal(r.ok, false);
  assert.match(r.error, /LPKSHHRH/);
});
