// Tests de mft — parser del $MFT de NTFS (timeline + timestomping).
//
// Verificación con ORÁCULO horneada: el fixture es un $MFT fabricado spec-exacto y
// PARSEADO con **analyzeMFT 3.1.1** (implementación independiente) durante el desarrollo;
// se asevera contra lo que analyzeMFT reportó. Embebido en base64 → npm test offline.
// 5 registros FILE (1024 B c/u):
//   0 $MFT · 1 notes.txt ($DATA residente 15 B) · 2 Documents (dir) ·
//   3 deleted_secret.docx (BORRADO, flags=0) · 4 malware.exe (TIMESTOMPED: SI 2009 < FN 2024)

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mft as M } from '../src/tools/mft.js';

const B64 = "RklMRTAAAwAAAAAAAAAAAAEAAQA4AAEAHAEAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAQAAAAAAAAAQAAAAYAAAAAAAAAAAAAEASAAAABgAAAAAwIl2RTzaAQDAiXZFPNoBAMCJdkU82gEAwIl2RTzaASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAaAAAAAAAAAAAAAIASgAAABgAAAAFAAAAAAABAADAiXZFPNoBAMCJdkU82gEAwIl2RTzaAQDAiXZFPNoBAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAABAMkAE0ARgBUAAAAAAAAAIAAAAAYAAAAAAAAAAAAAwAAAAAAGAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAEZJTEUwAAMAAAAAAAAAAAAFAAEAOAABADQBAAAABAAAAAAAAAAAAAAEAAAAAQAAAAEAAAAAAAAAEAAAAGAAAAAAAAAAAAABAEgAAAAYAAAAAGA/euJy2gEAHD6wlnPaAQAcPrCWc9oBAEABSFN02gEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAHAAAAAAAAAAAAACAFQAAAAYAAAABQAAAAAAAQAAYD964nLaAQBgP3rictoBAGA/euJy2gEAYD964nLaAQAAAAAAAAAADwAAAAAAAAAgAAAAAAAAAAkDbgBvAHQAZQBzAC4AdAB4AHQAAAAAAIAAAAAoAAAAAAAAAAAAAwAPAAAAGAAAAGhlbGxvIGZvcmVuc2ljcwD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQBGSUxFMAADAAAAAAAAAAAAAwABADgAAwAMAQAAAAQAAAAAAAAAAAAAAwAAAAIAAAABAAAAAAAAABAAAABgAAAAAAAAAAAAAQBIAAAAGAAAAACAu1PpI9oBAIC7U+kj2gEAgLtT6SPaAQCAu1PpI9oBIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAABwAAAAAAAAAAAAAgBUAAAAGAAAAAUAAAAAAAEAAIC7U+kj2gEAgLtT6SPaAQCAu1PpI9oBAIC7U+kj2gEAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAJA0QAbwBjAHUAbQBlAG4AdABzAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEARklMRTAAAwAAAAAAAAAAAAcAAQA4AAAAHAEAAAAEAAAAAAAAAAAAAAMAAAADAAAAAQAAAAAAAAAQAAAAYAAAAAAAAAAAAAEASAAAABgAAAAAwMHDalXaAQDAwcNqVdoBAMDBw2pV2gEAwMHDalXaASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAgAAAAAAAAAAAAAIAaAAAABgAAAAFAAAAAAABAADAwcNqVdoBAMDBw2pV2gEAwMHDalXaAQDAwcNqVdoBAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAEwNkAGUAbABlAHQAZQBkAF8AcwBlAGMAcgBlAHQALgBkAG8AYwB4AP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAEZJTEUwAAMAAAAAAAAAAAAJAAEAOAABACwBAAAABAAAAAAAAAAAAAAEAAAABAAAAAEAAAAAAAAAEAAAAGAAAAAAAAAAAAABAEgAAAAYAAAAAPw8XiAEygEA/DxeIATKAQD8PF4gBMoBAPw8XiAEygEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAHAAAAAAAAAAAAACAFgAAAAYAAAABQAAAAAAAQAA+KvNYaraAQD4q81hqtoBAPirzWGq2gEA+KvNYaraAQAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAsDbQBhAGwAdwBhAHIAZQAuAGUAeABlAIAAAAAgAAAAAAAAAAAAAwAEAAAAGAAAAE1akAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQA=";
const bytes = () => new Uint8Array(Buffer.from(B64, 'base64'));

test('parse: 5 registros FILE de 1024 B', () => {
  const p = M.parse(bytes());
  assert.equal(p.recSize, 1024);
  assert.equal(p.parsed, 5);
  assert.ok(p.records.every(r => r.fixupOk), 'fixup consistente');
});

test('rec1 notes.txt: nombre/padre/SI/FN/residente vs analyzeMFT', () => {
  const r = M.parse(bytes()).records[1];
  const fn = M.primaryFn(r.fnList);
  assert.equal(fn.name, 'notes.txt');
  assert.equal(fn.parentRef, 5);
  assert.equal(r.inUse, true);
  assert.equal(r.isDir, false);
  assert.equal(M.ftIso(r.si.crtime), '2024-03-10T12:00:00.000Z');
  assert.equal(M.ftIso(r.si.mtime), '2024-03-11T09:30:00.000Z');
  assert.equal(r.dataResident.size, 15);
});

test('rec2 Documents: directorio', () => {
  const r = M.parse(bytes()).records[2];
  assert.equal(r.isDir, true);
  assert.equal(M.primaryFn(r.fnList).name, 'Documents');
});

test('rec3 deleted_secret.docx: registro BORRADO', () => {
  const r = M.parse(bytes()).records[3];
  assert.equal(r.inUse, false);
  assert.equal(M.primaryFn(r.fnList).name, 'deleted_secret.docx');
});

test('rec4 malware.exe: TIMESTOMPING (SI 2009 < FN 2024)', () => {
  const r = M.parse(bytes()).records[4];
  const fn = M.primaryFn(r.fnList);
  assert.equal(M.ftIso(r.si.crtime), '2009-07-14T01:14:00.000Z');
  assert.equal(M.ftIso(fn.crtime), '2024-05-20T03:00:00.000Z');
  const sig = M.timestompSignals(r.si, fn);
  assert.ok(sig.some(s => /SI\.crtime anterior/.test(s)), 'detecta SI<FN');
});

test('summary: conteos coinciden con el oráculo', () => {
  const s = M.parse(bytes()).summary;
  assert.equal(s.deleted, 1);
  assert.equal(s.dirs, 1);
  assert.equal(s.resident, 3);
  assert.equal(s.timestomped.length, 1);
  assert.equal(s.timestomped[0].name, 'malware.exe');
  assert.equal(s.fixupBad, 0);
});

test('benigno: notes.txt NO marca timestomping (SI==FN)', () => {
  const r = M.parse(bytes()).records[1];
  assert.equal(M.timestompSignals(r.si, M.primaryFn(r.fnList)).length, 0);
});

test('detectRecSize + basura', () => {
  assert.equal(M.detectRecSize(bytes()), 1024);
  assert.equal(M.parse(new Uint8Array([1,2,3,4,5,6,7,8])).records.length, 0);
});
